import json
import re
from services.gemini_service import model

async def extract_details_and_feedback(resume_text: str) -> dict:
    prompt = f"""
    You are an expert AI recruiter and resume parser. Analyze the following resume text and extract candidate details as a structured JSON object.
    
    CRITICAL RELIABILITY AND ACCURACY DIRECTIVES:
    1. Extract ONLY facts that are directly and explicitly stated in the resume text. Do NOT assume, estimate, or make up any details (like CGPA, scores, skills, experiences, projects, or dates) that are not explicitly written.
    2. If a specific field or section is not found in the resume, you must return null or "Not Found" for strings, or an empty list/null for arrays. Do NOT guess, assume, or output generic/placeholder values.
    3. Do NOT make assumptions about technology versions or candidate roles if they are not explicitly present.
    
    Fields to extract:
    - name: Full name (string). If not found, return null or "Not Found".
    - email: Email address (string). If not found, return null or "Not Found".
    - phone: Contact phone number (string). If not found, return null or "Not Found".
    - tenth_percentage: 10th class percentage/score (float, 0.0 to 100.0, default 0.0). Only extract if explicitly stated in text.
    - twelfth_percentage: 12th class percentage/score (float, 0.0 to 100.0, default 0.0). Only extract if explicitly stated in text.
    - graduation_cgpa: Graduation CGPA (float, 0.0 to 10.0, default 0.0). If percentage like 80% is given in education, convert to CGPA (e.g. 8.0). Only extract if explicitly stated in text.
    - experience_years: Total years of professional experience as a float. Look for job durations. If none or not clearly stated, return 0.0.
    - skills: List of programming languages, frameworks, developer tools, database engines, etc. (list of strings).
    - education: List of objects representing education history. Each object should have:
        - degree: Degree name (e.g. B.Tech, Master of Science) (string)
        - field_of_study: Major/Specialization (string)
        - institution: University/College name (string)
        - year_of_completion: Graduation year (string or integer)
        - score: Score/GPA/CGPA/Percentage if explicitly mentioned (string)
    - experience: List of objects representing professional work experience. Each object should have:
        - job_title: Job title (string)
        - company: Company name (string)
        - duration: Duration of employment (e.g. "June 2021 - Present") (string)
        - responsibilities: List of key responsibilities/contributions (list of strings)
    - projects: List of objects representing projects. Each object should have:
        - name: Project name (string)
        - description: Project description (string)
        - technologies_used: List of technologies used (list of strings)
    - certificates: List of certifications (list of strings). If not found, return empty list.
    - achievements: List of accomplishments/achievements (list of strings). If not found, return empty list.
    
    Qualitative Assessment Scores:
    - education_quality_score: Float between 0.0 and 100.0 evaluating the relevance and calibre of education history.
    - experience_relevance_score: Float between 0.0 and 100.0 evaluating the relevance and alignment of the candidate's work history for standard engineering/technology positions.
    - projects_quality_score: Float between 0.0 and 100.0 evaluating the technical depth and professional relevance of their projects.
    - certifications_relevance_score: Float between 0.0 and 100.0 evaluating the credibility and relevance of their certifications.
    
    ATS Scoring Indicators:
    - grammar_score: Float between 0.0 and 100.0 reflecting grammatical accuracy and spelling.
    - grammar_suggestions: List of specific spelling/grammar improvements in the text (list of strings). Leave empty if perfect.
    - formatting_score: Float between 0.0 and 100.0 reflecting clarity, structure, and professional look.
    - formatting_issues: List of formatting/layout issues found in the text (list of strings). Leave empty if none.
    - missing_sections: List of standard missing resume sections (e.g., "Projects", "Certifications", "Contact Info", "Education", "Experience") (list of strings). Only list if they are truly missing from the text.
    - keyword_suggestions: List of relevant keywords/technologies the resume should add (list of strings).
    - resume_suggestions: List of general improvements (list of strings).
    
    AI Generated Content Detection:
    - ai_probability: Float between 0.0 and 100.0 representing the probability that this resume was written/generated by AI (ChatGPT, Gemini, Claude, etc.), based on writing style, repetitiveness, standard templates, and linguistic analysis.
    - ai_result: Must be exactly "Likely Human Written" if ai_probability < 50.0, otherwise "Likely AI Generated".
    - ai_explanation: A brief 1-2 sentence linguistic analysis explaining why this classification was made.

    - feedback: A paragraph summarizing:
      1. Strengths: Core competencies.
      2. Weaknesses: Shortcomings.
      3. Suggestions: Actionable recommendations.
      Provide this feedback as a formatted string with bullet points.

    Provide ONLY valid JSON. Return the raw JSON block. Do not wrap the JSON output in markdown tags (no ```json).

    Resume Text:
    {resume_text}
    """

    try:
        response = await model.generate_content_async(
            prompt,
            generation_config={"response_mime_type": "application/json", "temperature": 0.0}
        )
        text = response.text.strip()
        
        # Clean any markdown wrapping
        if text.startswith("```"):
            text = re.sub(r"^```(json)?", "", text)
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()
        
        data = json.loads(text)
        
        # Ensure default keys
        data.setdefault("name", "Unknown Candidate")
        data.setdefault("email", "Not Found")
        data.setdefault("phone", "Not Found")
        data.setdefault("tenth_percentage", 0.0)
        data.setdefault("twelfth_percentage", 0.0)
        data.setdefault("graduation_cgpa", 0.0)
        data.setdefault("experience_years", 0.0)
        data.setdefault("skills", [])
        data.setdefault("education", [])
        data.setdefault("experience", [])
        data.setdefault("projects", [])
        data.setdefault("certificates", [])
        data.setdefault("achievements", [])
        data.setdefault("education_quality_score", 70.0)
        data.setdefault("experience_relevance_score", 70.0)
        data.setdefault("projects_quality_score", 70.0)
        data.setdefault("certifications_relevance_score", 70.0)
        data.setdefault("grammar_score", 90.0)
        data.setdefault("grammar_suggestions", [])
        data.setdefault("formatting_score", 90.0)
        data.setdefault("formatting_issues", [])
        data.setdefault("missing_sections", [])
        data.setdefault("keyword_suggestions", [])
        data.setdefault("resume_suggestions", [])
        data.setdefault("ai_probability", 15.0)
        data.setdefault("ai_result", "Likely Human Written")
        data.setdefault("ai_explanation", "Linguistic patterns indicate natural variation in sentence structure.")
        data.setdefault("feedback", "No feedback available.")
        
        return data
    except Exception as e:
        print("Error parsing Gemini JSON output:", e)
        return {
            "name": "Unknown Candidate",
            "email": "Not Found",
            "phone": "Not Found",
            "tenth_percentage": 0.0,
            "twelfth_percentage": 0.0,
            "graduation_cgpa": 0.0,
            "experience_years": 0.0,
            "skills": [],
            "education": [],
            "experience": [],
            "projects": [],
            "certificates": [],
            "achievements": [],
            "education_quality_score": 50.0,
            "experience_relevance_score": 50.0,
            "projects_quality_score": 50.0,
            "certifications_relevance_score": 50.0,
            "grammar_score": 80.0,
            "grammar_suggestions": ["Ensure active verbs are used throughout."],
            "formatting_score": 80.0,
            "formatting_issues": ["Unable to fully analyze formatting details."],
            "missing_sections": [],
            "keyword_suggestions": [],
            "resume_suggestions": [],
            "ai_probability": 20.0,
            "ai_result": "Likely Human Written",
            "ai_explanation": "Default evaluation: fallback parsing active.",
            "feedback": f"Failed to extract details: {str(e)}"
        }
