import json
import re
from services.gemini_service import model

async def extract_details_and_feedback(resume_text: str) -> dict:
    prompt = f"""
    You are an expert AI recruiter and writing style/linguistic analyst. Analyze the following resume text and extract details as a structured JSON object.
    
    CRITICAL RELIABILITY AND ACCURACY DIRECTIVES:
    1. Extract ONLY facts that are directly and explicitly stated in the resume text. Do NOT assume, estimate, or make up any details (like CGPA, scores, skills, experiences, projects, or dates) that are not explicitly written.
    2. If the candidate's 10th class percentage, 12th class percentage, or graduation CGPA is not explicitly written in the resume text, you MUST return 0.0 for that field. Do NOT guess or default to any passing or high grades.
    3. Do NOT make assumptions about technology versions or candidate roles if they are not explicitly present.
    4. Grammar suggestions, formatting issues, and keyword recommendations MUST be highly specific to the actual text of this resume. Do NOT provide generic suggestions or list boilerplate formatting/grammar tips that are not applicable to the text.
    5. Avoid any generic AI hallucinated commentary. The feedback summary must only state findings determined directly from the uploaded CV.
    
    Fields to extract:
    - name: Full name (string). If not found, use "Unknown Candidate".
    - email: Email address (string). If not found, use "".
    - tenth_percentage: 10th class percentage/score (float, 0.0 to 100.0, default 0.0). Only extract if explicitly stated in text.
    - twelfth_percentage: 12th class percentage/score (float, 0.0 to 100.0, default 0.0). Only extract if explicitly stated in text.
    - graduation_cgpa: Graduation CGPA (float, 0.0 to 10.0, default 0.0). If percentage like 80% is given in education, convert to CGPA (e.g. 8.0). Only extract if explicitly stated in text.
    - experience_years: Total years of professional experience as a float. Look for job durations. If none or not clearly stated, return 0.0.
    - skills: List of programming languages, frameworks, developer tools, database engines, etc. (list of strings).
    - projects: List of names or descriptions of projects mentioned (list of strings).
    - certificates: List of certifications (list of strings).
    - achievements: List of accomplishments (list of strings).
    - strengths: List of strengths/core competencies (list of strings).
    - weaknesses: List of weakness areas (list of strings).
    
    ATS Scoring Indicators:
    - grammar_score: Float between 0.0 and 100.0 reflecting grammatical accuracy and spelling.
    - grammar_suggestions: List of specific spelling/grammar improvements in the text (list of strings). Leave empty if perfect.
    - formatting_score: Float between 0.0 and 100.0 reflecting clarity, structure, and professional look.
    - formatting_issues: List of formatting/layout issues found in the text (list of strings). Leave empty if none.
    - missing_sections: List of standard missing resume sections (e.g., "Projects", "Certifications", "Contact Info", "Education", "Experience") (list of strings). Only list if they are truly missing from the text.
    - keyword_suggestions: List of relevant keywords/technologies the resume should add (list of strings).
    - resume_suggestions: List of general improvements (list of strings).
    
    AI Generated Content Detection:
    - ai_probability: Float between 0.0 and 100.0 representing the probability that this resume was written/generated by AI (ChatGPT, Gemini, Claude, etc.), based on writing style, repetitiveness, standard templates, and linguistic analysis.
    - ai_result: Must be exactly "Likely Human Written" if ai_probability < 50.0, otherwise "Likely AI Generated".
    - ai_explanation: A brief 1-2 sentence linguistic analysis explaining why this classification was made.

    - feedback: A paragraph summarizing:
      1. Strengths: Core competencies.
      2. Weaknesses: Shortcomings.
      3. Suggestions: Actionable recommendations.
      Provide this feedback as a formatted string with bullet points.

    Provide ONLY valid JSON. Return the raw JSON block. Do not wrap the JSON output in markdown tags (no ```json).

    Resume Text:
    {resume_text}
    """

    try:
        response = await model.generate_content_async(
            prompt,
            generation_config={"response_mime_type": "application/json", "temperature": 0.0}
        )
        text = response.text.strip()
        
        # Clean any markdown wrapping
        if text.startswith("```"):
            text = re.sub(r"^```(json)?", "", text)
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()
        
        data = json.loads(text)
        
        # Ensure default keys
        data.setdefault("name", "Unknown Candidate")
        data.setdefault("email", "")
        data.setdefault("tenth_percentage", 0.0)
        data.setdefault("twelfth_percentage", 0.0)
        data.setdefault("graduation_cgpa", 0.0)
        data.setdefault("experience_years", 0.0)
        data.setdefault("skills", [])
        data.setdefault("projects", [])
        data.setdefault("certificates", [])
        data.setdefault("achievements", [])
        data.setdefault("strengths", [])
        data.setdefault("weaknesses", [])
        data.setdefault("grammar_score", 90.0)
        data.setdefault("grammar_suggestions", [])
        data.setdefault("formatting_score", 90.0)
        data.setdefault("formatting_issues", [])
        data.setdefault("missing_sections", [])
        data.setdefault("keyword_suggestions", [])
        data.setdefault("resume_suggestions", [])
        data.setdefault("ai_probability", 15.0)
        data.setdefault("ai_result", "Likely Human Written")
        data.setdefault("ai_explanation", "Linguistic patterns indicate natural variation in sentence structure.")
        data.setdefault("feedback", "No feedback available.")
        
        return data
    except Exception as e:
        print("Error parsing Gemini JSON output:", e)
        return {
            "name": "Unknown Candidate",
            "email": "",
            "tenth_percentage": 0.0,
            "twelfth_percentage": 0.0,
            "graduation_cgpa": 0.0,
            "experience_years": 0.0,
            "skills": [],
            "projects": [],
            "certificates": [],
            "achievements": [],
            "strengths": [],
            "weaknesses": [],
            "grammar_score": 80.0,
            "grammar_suggestions": ["Ensure active verbs are used throughout."],
            "formatting_score": 80.0,
            "formatting_issues": ["Unable to fully analyze formatting details."],
            "missing_sections": [],
            "keyword_suggestions": [],
            "resume_suggestions": [],
            "ai_probability": 20.0,
            "ai_result": "Likely Human Written",
            "ai_explanation": "Default evaluation: fallback parsing active.",
            "feedback": f"Failed to extract details: {str(e)}"
        }
